name: Debian Packaging CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.sha }}
        fetch-depth: 0
        fetch-tags: true
    - name: Get tags from upstream, if needed
      if: github.repository != 'Azure/azure-nvme-utils'
      run: |
        git remote add upstream https://github.com/Azure/azure-nvme-utils.git
        git fetch upstream --tags
    - name: Setup
      run: |
        sudo apt update
        sudo apt install gcc pandoc cmake devscripts debhelper -y
    - name: Build debs
      run: |
        DEBEMAIL="Azure NVMe Utils CI <azure/azure-nvme-utils@github.com>" ./scripts/build-deb.sh
    - name: Lintian check
      run: |
        lintian out/*.deb
    - name: Install debs
      run: |
        sudo dpkg -i out/*.deb
    - name: Verify installation
      run: |
        set -x
        dpkg -L azure-nvme-utils
        test -f /usr/share/initramfs-tools/hooks/azure-disk
        test -f /usr/share/man/man8/azure-nvme-id.8.gz
        test -f /usr/sbin/azure-nvme-id
        test -f /lib/udev/rules.d/80-azure-disk.rules
        azure-nvme-id --version
