name: Debian Packaging CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - debian:12
          - debian:sid
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.sha }}
        fetch-depth: 0
        fetch-tags: true
    - name: Get tags from upstream, if needed
      if: github.repository != 'Azure/azure-vm-utils'
      run: |
        git remote add upstream https://github.com/Azure/azure-vm-utils.git
        git fetch upstream --tags
    - name: Build debs
      run: |
        ./scripts/build-deb.sh
    - name: Lintian check
      run: |
        lintian --fail-on error,warning out/*.deb
    - name: Install debs
      run: |
        sudo dpkg -i out/*.deb
    - name: Verify installation
      run: |
        set -x
        dpkg -L azure-vm-utils
        test -f /usr/lib/systemd/network/01-azure-unmanaged-sriov.network
        test -f /usr/lib/udev/rules.d/10-azure-unmanaged-sriov.rules
        test -f /usr/lib/udev/rules.d/80-azure-disk.rules
        test -x /usr/sbin/azure-nvme-id
        test -x /usr/sbin/azure-vm-utils-selftest
        test -f /usr/share/initramfs-tools/hooks/azure-disk
        test -f /usr/share/initramfs-tools/hooks/azure-unmanaged-sriov
        test -f /usr/share/man/man8/azure-nvme-id.8.gz
        test -f /usr/share/man/man8/azure-vm-utils-selftest.8.gz
        azure-nvme-id --version
        azure-vm-utils-selftest --skip-imds-validation --skip-symlink-validation
